(ns tarantool.errinj
  "Tarantool error injections.")

(def codes
  "A list of error injections that used in Tarantool.
   Source: lib/core/errinj.h"
  [:ERRINJ_TESTING
   :ERRINJ_WAL_IO
   :ERRINJ_WAL_SYNC
   :ERRINJ_WAL_ROTATE
   :ERRINJ_WAL_WRITE
   :ERRINJ_WAL_WRITE_DISK
   :ERRINJ_WAL_WRITE_EOF
   :ERRINJ_WAL_DELAY
   ;:ERRINJ_WAL_WRITE_PARTIAL, ERRINJ_INT, {.iparam = -1}) \
   ;:ERRINJ_WAL_DELAY_COUNTDOWN, ERRINJ_INT, {.iparam = -1}) \
   ;:ERRINJ_WAL_FALLOCATE, ERRINJ_INT, {.iparam = 0}) \
   ;:ERRINJ_WAL_WRITE_COUNT, ERRINJ_INT, {.iparam = 0}) \
   :ERRINJ_INDEX_ALLOC
   :ERRINJ_TUPLE_ALLOC
   :ERRINJ_TUPLE_FIELD
   :ERRINJ_VY_RUN_WRITE
   :ERRINJ_VY_RUN_WRITE_DELAY
   :ERRINJ_VY_RUN_DISCARD
   ;:ERRINJ_VY_INDEX_DUMP, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_VY_TASK_COMPLETE
   :ERRINJ_VY_READ_PAGE
   :ERRINJ_VY_READ_PAGE_DELAY
   ;:ERRINJ_VY_READ_PAGE_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
   ;:ERRINJ_VY_SQUASH_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
   ;:ERRINJ_VY_SCHED_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
   :ERRINJ_VY_GC
   :ERRINJ_VY_LOG_FLUSH
   :ERRINJ_VY_LOG_FLUSH_DELAY
   :ERRINJ_RELAY_SEND_DELAY
   ;:ERRINJ_RELAY_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
   ;:ERRINJ_RELAY_REPORT_INTERVAL, ERRINJ_DOUBLE, {.dparam = 0}) \
   :ERRINJ_RELAY_FINAL_SLEEP
   :ERRINJ_RELAY_FINAL_JOIN
   :ERRINJ_REPLICA_JOIN_DELAY
   :ERRINJ_PORT_DUMP
   :ERRINJ_XLOG_GARBAGE
   :ERRINJ_XLOG_META
   ;:ERRINJ_XLOG_READ, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_VYRUN_DATA_READ
   :ERRINJ_CHECK_FORMAT_DELAY
   ;:ERRINJ_BUILD_INDEX, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_BUILD_INDEX_DELAY
   :ERRINJ_VY_POINT_ITER_WAIT
   ;:ERRINJ_RELAY_EXIT_DELAY, ERRINJ_DOUBLE, {.dparam = 0}) \
   :ERRINJ_VY_DELAY_PK_LOOKUP
   ;:ERRINJ_VY_RUN_WRITE_STMT_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
   :ERRINJ_IPROTO_TX_DELAY
   :ERRINJ_HTTPC_EXECUTE
   :ERRINJ_LOG_ROTATE
   :ERRINJ_SNAP_WRITE_DELAY
   :ERRINJ_SNAP_COMMIT_DELAY
   :ERRINJ_HTTP_RESPONSE_ADD_WAIT
   :ERRINJ_VY_LOG_FILE_RENAME
   :ERRINJ_VY_RUN_FILE_RENAME
   :ERRINJ_VY_INDEX_FILE_RENAME
   ;:ERRINJ_RELAY_BREAK_LSN, ERRINJ_INT, {.iparam = -1}) \
   ;:ERRINJ_WAL_BREAK_LSN, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_VY_DUMP_DELAY
   :ERRINJ_VY_COMPACTION_DELAY
   ;:ERRINJ_TUPLE_FORMAT_COUNT, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_MEMTX_DELAY_GC
   ;:ERRINJ_SIO_READ_MAX, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_SQL_NAME_NORMALIZATION
   ;:ERRINJ_COIO_SENDFILE_CHUNK, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_SWIM_FD_ONLY
   ;:ERRINJ_DYN_MODULE_COUNT, ERRINJ_INT, {.iparam = 0}) \
   :ERRINJ_FIBER_MADVISE
   ;:ERRINJ_FIBER_MPROTECT, ERRINJ_INT, {.iparam = -1}) \
   :ERRINJ_RELAY_FASTER_THAN_TX
   :ERRINJ_INDEX_RESERVE
   :ERRINJ_TXN_COMMIT_ASYNC
   ;:ERRINJ_VY_STMT_ALLOC, ERRINJ_INT, {.iparam = -1})\
   :ERRINJ_VY_READ_VIEW_MERGE_FAIL
   :ERRINJ_VY_WRITE_ITERATOR_START_FAIL
   ;:ERRINJ_VY_RUN_OPEN, ERRINJ_INT, {.iparam = -1})\
   :ERRINJ_AUTO_UPGRADE
   :ERRINJ_COIO_WRITE_CHUNK
   :ERRINJ_APPLIER_SLOW_ACK])
